# flake8: noqa
"""empty message

Revision ID: 2dbc8088936
Revises: 2dc297da182
Create Date: 2015-06-11 20:42:46.630809

"""

# revision identifiers, used by Alembic.
revision = '2dbc8088936'
down_revision = '2dc297da182'


from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deed_id', sa.Integer(), nullable=True),
    sa.Column('conveyancer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case')
    ### end Alembic commands ###
