# flake8: noqa
"""empty message

Revision ID: 2dc297da182
Revises: None
Create Date: 2015-06-11 20:30:23.949808

"""

# revision identifiers, used by Alembic.
revision = '2dc297da182'
down_revision = None


from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
