# flake8: noqa
"""empty message

Revision ID: 33eaaa530ac
Revises: 34a88bd296e
Create Date: 2015-08-18 12:33:44.366297

"""

# revision identifiers, used by Alembic.
revision = '33eaaa530ac'
down_revision = '34a88bd296e'


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('borrowers', postgresql.ARRAY(sa.Integer()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'borrowers')
    ### end Alembic commands ###
