# flake8: noqa
"""empty message

Revision ID: 4bf039b78ac
Revises: 748d5fc8c8
Create Date: 2015-09-10 13:28:41.644445

"""

# revision identifiers, used by Alembic.
revision = '4bf039b78ac'
down_revision = '58c5cfd81c3'


from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrower', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrower', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
