# flake8: noqa
"""empty message

Revision ID: 58c5cfd81c3
Revises: 748d5fc8c8
Create Date: 2015-09-02 10:12:04.131325

"""

# revision identifiers, used by Alembic.
revision = '58c5cfd81c3'
down_revision = '748d5fc8c8'


from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('title_number', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('extended', sa.String(), nullable=True),
    sa.Column('locality', sa.String(), nullable=False),
    sa.Column('postcode', sa.String(), nullable=False),
    sa.Column('tenure', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    ### end Alembic commands ###
